apiVersion: apps/v1
kind: Deployment
metadata:
 name: python-app
 labels:
   app: python-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: python-app
 template:
   metadata:
     labels:
       app: python-app
   spec:
     containers:
       - name: python-app-hello-world
         image:  gcr.io/<GCP_PROJECT_NAME>/python-app:GITHUB_SHA
         ports:
           - containerPort: 8080
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: test.example.com
      http:
        paths:
        - backend:
            service:
              name: python-service
              port: 
                number: 8080
          path: /
          pathType: ImplementationSpecific
